services:
  app: # Development environment
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development 
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=${DB_PORT:-5432}
      - DEVELOPMENT_DATABASE=${DEVELOPMENT_DATABASE}'
    command: ["bash", "-c", "rm -f /app/tmp/pids/server.pid && rails server -b 0.0.0.0"]
  
  db: # Shared database for all environments
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DEVELOPMENT_DATABASE} 
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data 
    ports:
      - "${DB_PORT:-5432}:5432"

volumes:
  postgres_data_dev: 
