services:
  web: # Development environment
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_HOST: localhost #to_do_list
      DB_PORT: 5432
      RAILS_ENV: development
    command: ["bash", "-c", "rm -f /app/tmp/pids/server.pid && rails server -b 0.0.0.0"]

  db: # Shared database for all environments
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: to_do_list_v360_development
    volumes:
      - postgres_data:/var/lib/postgresql/data

  test: # Test environment
    build: .
    volumes:
      - .:/app
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      RAILS_ENV: test
    entrypoint: ["./entrypoint.sh"]
    command: ["rails", "test"]

  production:
    adapter: postgresql
    encoding: unicode
    pool: 5
    url: <%= ENV['DATABASE_URL'] %>


volumes:
  postgres_data: # Persistent storage for database
