name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3' 
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

  lint:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3' 
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Run Lint
        run: bundle exec rubocop
  
  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Set up Environment Variables
        env:
          DB_USERNAME: "postgres"
          DB_PASSWORD: "postgres"
          DB_HOST: "localhost"
          DB_PORT: "5432"
          DEVELOPMENT_DATABASE: "to_do_list_development"
          TEST_DATABASE: "to_do_list_test"
        run: echo "Environment variables set"

      - name: Set up Database
        env:
          DB_USERNAME: "postgres"
          DB_PASSWORD: "postgres"
          DB_HOST: local"host
          DB_PORT: "5432"
          RAILS_ENV: "test"
        run: |
          bundle exec rails db:create 
          bundle exec rails db:seed
          bundle exec rails rails db:migrate RAILS_ENV=test

      - name: Run Tests
        run: bundle exec rails test
