name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3' 
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

  lint:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3' 
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Run Lint
        run: bundle exec rubocop
  
  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Set up Environment Variables
        env:
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DEVELOPMENT_DATABASE: ${{ secrets.DEVELOPMENT_DATABASE }}
          TEST_DATABASE: ${{ secrets.TEST_DATABASE }}
        run: echo "Environment variables set"

      - name: Set up Database
        env:
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          RAILS_ENV: test
        run: |
          bundle exec rails db:create 
          bundle exec rails db:seed
          bundle exec rails rails db:migrate RAILS_ENV=test

      - name: Run Tests
        run: bundle exec rails test
