name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3' 
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

  lint:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3' 
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Run Lint
        run: bundle exec rubocop
  
  test:
    runs-on: ubuntu-latest
    needs: build
    services:
      db:
        image: postgres:13
        ports:
          - 5432:5432
        options: 
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server
    steps:
      - uses: actions/checkout@v2
      - name: Checkout code
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
      - name: Run Tests
        env:
          DATABASE_URL: postgres://postgres:@localhost:5432/test
          REDIS_URL: redis://localhost:6379
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: 
          sudo apt-get -yqq install libpq-dev
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rails db:create 
          bundle exec rails db:migrate
          bundle exec rails test
