name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: to_do_list_development
        ports:
          - 5432:5432
        volumes:
          - postgres_data_dev:/var/lib/postgresql/data

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and run Docker containers
        run: |
          docker-compose up -d
          sleep 10 # Aguarda o banco de dados iniciar

      - name: Run Lint
        run: |
          docker-compose exec web rubocop

      - name: Run Tests
        run: |
          docker-compose exec web rails db:create RAILS_ENV=test
          docker-compose exec web rails db:migrate RAILS_ENV=test
          docker-compose exec web rails test

      - name: Shutdown Docker containers
        run: docker-compose down
